FROM python:3.11-slim

WORKDIR /app

ENV OLLAMA_CLIENT_URL=http://host.docker.internal:11434
ENV LMSTUDIO_CLIENT=http://host.docker.internal:1234/v1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y poppler-utils
COPY ./simple_rag_api_example.py .

CMD ["python", "simple_rag_api_example.py"]

# Run using this command : docker run --add-host=host.docker.internal:host-gateway your_image
